### ISSUE TITLE
Home Assistant Core 2022.3 had some breaking changes

### ISSUE THREAD

**Issue by rclark213** [neggert/hass-egauge#118] opened 2022-03-03 00:46 UTC
## Version of the custom_component

0.4.0

## Configuration

```yaml
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 4:05:14 PM (3 occurrences)
Last logged: 4:05:19 PM

Unable to install package egauge-async==0.1.1: ERROR: Cannot install egauge-async==0.1.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Logger: homeassistant.setup
Source: setup.py:155
First occurred: 4:05:19 PM (1 occurrences)
Last logged: 4:05:19 PM

Setup failed for egauge: Requirements for egauge not found: ['egauge-async==0.1.1'].
```
Not sure where else I should be looking for helpful logs. 

## Describe the bug

After upgrading to Home Assistant Core 2022.3, the error logs above showed up. Additionally, all eGauge sensors are now showing as "unavailable". 

## Debug log

```text

Add your logs here.

```

**Comment by Lymkin** [comment] 2022-03-03 18:05
I have the same issue.

**Comment by billraff** [comment] 2022-03-04 21:46
Yes, came here to see if anyone else was seeing the same.

**Comment by ZacFranken** [comment] 2022-03-06 04:28
Same error here.

**Comment by neggert** [comment] 2022-03-06 20:46
Looking into it

**Comment by neggert** [comment] 2022-03-06 22:57
This should be fixed in the new-released version 0.4.1. Feel free to re-open the issue if the problem isn't resolved.

**Closed by neggert** 2022-03-06 22:57 UTC

**Comment by rclark213** [comment] 2022-03-07 00:18
> This should be fixed in the new-released version 0.4.1. Feel free to re-open the issue if the problem isn't resolved.

Thanks, seems to have fixed it! I really appreciate the work you've put into this.

**Comment by phidauex** [comment] 2022-03-07 18:59
Thanks for the fast patch! I had just forked to poke at it and see if I could help, then I saw your new release pop right up. Appreciate the work you are doing to maintain this integration!

**Comment by Lymkin** [comment] 2022-03-07 21:02
Thanks for the fix and making this integration!
